import type { NextPage } from 'next';
import Head from 'next/head';

// Components import
import { ResumeHeader, ResumeSections } from '@components/sections';

import { Container } from '@mui/system';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Resumetor</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Container>
                    <ResumeHeader />
                    <ResumeSections />
                </Container>
            </main>
        </>
    );
};

export default Home;
