import type { NextPage } from 'next';
import Head from 'next/head';

// Components import
import { PersonalInfo } from '@components/sections';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Resumetor</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="home__container">
                <PersonalInfo />
            </main>
        </>
    );
};

export default Home;
